server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://1f1562b3-3373-483f-adfe-e59d45b24d7e.external.kr1.mysql.rds.nhncloudservice.com:10000/textme
    username: textme
    password: textme12!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        show_sql: true
    open-in-view: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
security:
  jwt:
    token:
      secretKey: a4b8b807752bca58e4b12e8a01e1842a4df27e75ba49176b5833bde57d28d55c7f5b5c4fcd6b89b5e94f044c99afaefc461589ee9fd26c3e167d8954c06980d
      expirationMs: 36000000
      refreshExpirationMs: 5184000000

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: desc

cloud:
  aws:
    credentials:
      accessKey: AKIAR3VO3W3NQI7IQ3FE
      secretKey: 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
    s3:
      bucket: textme-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
