name: Build Frontend Image

on:
  pull_request:
    branches:
      - production
      - master
    paths:
      - "frontend/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install
        run: yarn install

      - name: Build
        run: yarn run build

      - name: pm2
        run: pm2 reload next-js
        env:
          CI: true
