name: Build Backend Image

on:
  push:
    branches: [ production, master ]
    paths:
      - "backend/**"
  pull_request:
    branches: [ production, master ]
    paths:
      - "backend/**"

permissions:
  contents: read

defaults:
  run:
    working-directory: "backend/text-me"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set environment variables
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> "$GITHUB_ENV"
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> "$GITHUB_ENV"
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> "$GITHUB_ENV"
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> "$GITHUB_ENV"
          echo "JWT_EXPIRY=${{ secrets.JWT_EXPIRY }}" >> "$GITHUB_ENV"
          echo "REFRESH_EXPIRY=${{ secrets.REFRESH_EXPIRY }}" >> "$GITHUB_ENV"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> "$GITHUB_ENV"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> "$GITHUB_ENV"
          echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> "$GITHUB_ENV"
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> "$GITHUB_ENV"
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> "$GITHUB_ENV"
          echo "KAKAO_SCOPE=${{ secrets.KAKAO_SCOPE }}" >> "$GITHUB_ENV"
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> "$GITHUB_ENV"
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> "$GITHUB_ENV"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> "$GITHUB_ENV"



      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with jib
        run: |
          ./gradlew jib \
          -Djib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }} \
          -Djib.to.auth.password=${{ secrets.DOCKERHUB_PASSWORD }} \
          -Djib.to.image="${{ secrets.DOCKERHUB_USERNAME }}/text-me-docker-repo:${GITHUB_REF##*/}"
          
          ./gradlew jibDockerBuild \
          -Djib.container.environment=DB_URL="$DB_URL",DB_USERNAME="$DB_USERNAME",DB_PASSWORD="$DB_PASSWORD", \
          JWT_KEY="$JWT_KEY",JWT_EXPIRY="$JWT_EXPIRY",REFRESH_EXPIRY="$REFRESH_EXPIRY", \
          AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID",AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY", \
          KAKAO_CLIENT_SECRET="$KAKAO_CLIENT_SECRET",KAKAO_CLIENT_ID="$KAKAO_CLIENT_ID", \
          KAKAO_REDIRECT_URI="$KAKAO_REDIRECT_URI",KAKAO_SCOPE="$KAKAO_SCOPE", \
          REDIS_HOST="$REDIS_HOST",REDIS_PORT="$REDIS_PORT", \
          GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
        shell: bash
