name: Deploy Backend

on:
  push:
    branches:
      - production
  workflow_dispatch:

defaults:
  run:
    working-directory: "backend/text-me"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: SSH setting
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            whoami
            sudo docker pull {${{ secrets.DOCKERHUB_USERNAME }}/text-me-docker-repo}:${GITHUB_REF##*/}
            sudo docker tag {${{ secrets.DOCKERHUB_USERNAME }}/text-me-docker-repo}:${GITHUB_REF##*/} {${{ secrets.DOCKERHUB_USERNAME }}/text-me-docker-repo}:${GITHUB_REF##*/}
            sudo docker stop text-me-api
            sudo docker run -d --rm --name text-me-api -p 8080:8080 {${{ secrets.DOCKERHUB_USERNAME }}/text-me-docker-repo}:${GITHUB_REF##*/}
