name: Deploy Frontend

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}

      - name: Adding known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/ .ssh/known_hosts

      - name: Run deploy script
        run: ssh ubuntu@${{ secrets.SERVER_IP }} bash deploy.sh
