name: Deploy Frontend

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Deploy
        run: curl ${{ secrets.FE_PROD_DEPLOY_REQUEST_URL }}
